export enum ProductListActionType {
  REQUEST = 'PRODUCT_LIST_REQUEST',
  SUCCESS = 'PRODUCT_LIST_SUCCESS',
  FAIL = 'PRODUCT_LIST_FAIL',
}

export enum ProductDetailActionType {
  REQUEST = 'PRODUCT_DETAIL_REQUEST',
  SUCCESS = 'PRODUCT_DETAIL_SUCCESS',
  FAIL = 'PRODUCT_DETAIL_FAIL',
}

export enum ProductDeleteActionType {
  REQUEST = 'PRODUCT_DELETE_REQUEST',
  SUCCESS = 'PRODUCT_DELETE_SUCCESS',
  FAIL = 'PRODUCT_DELETE_FAIL',
}

export enum ProductCreateActionType {
  REQUEST = 'PRODUCT_CREATE_REQUEST',
  SUCCESS = 'PRODUCT_CREATE_SUCCESS',
  FAIL = 'PRODUCT_CREATE_FAIL',
  RESET = 'PRODUCT_CREATE_RESET',
}

export enum ProductUpdateActionType {
  REQUEST = 'PRODUCT_UPDATE_REQUEST',
  SUCCESS = 'PRODUCT_UPDATE_SUCCESS',
  FAIL = 'PRODUCT_UPDATE_FAIL',
  RESET = 'PRODUCT_UPDATE_RESET',
}

export enum ProductCreateReviewActionType {
  REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST',
  SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS',
  FAIL = 'PRODUCT_CREATE_REVIEW_FAIL',
  RESET = 'PRODUCT_CREATE_REVIEW_RESET',
}

export enum ProductTopActionType {
  REQUEST = 'PRODUCT_TOP_REQUEST',
  SUCCESS = 'PRODUCT_TOP_SUCCESS',
  FAIL = 'PRODUCT_TOP_FAIL',
}
