export enum OrderCreateActionType {
  REQUEST = 'ORDER_CREATE_REQUEST',
  SUCCESS = 'ORDER_CREATE_SUCCESS',
  FAIL = 'ORDER_CREATE_FAIL',
}
export enum OrderDetailActionType {
  REQUEST = 'ORDER_DETAIL_REQUEST',
  SUCCESS = 'ORDER_DETAIL_SUCCESS',
  FAIL = 'ORDER_DETAIL_FAIL',
}
export enum OrderPaidActionType {
  REQUEST = 'ORDER_PAID_REQUEST',
  SUCCESS = 'ORDER_PAID_SUCCESS',
  FAIL = 'ORDER_PAID_FAIL',
  RESET = 'ORDER_PAID_RESET',
}

export enum OrderListMyActionType {
  REQUEST = 'MY_ORDER_REQUEST',
  SUCCESS = 'MY_ORDER_SUCCESS',
  FAIL = 'MY_ORDER_FAIL',
  RESET = 'MY_ORDER_RESET',
}

export enum OrderListActionType {
  REQUEST = 'ORDER_LIST_REQUEST',
  SUCCESS = 'ORDER_LIST_SUCCESS',
  FAIL = 'ORDER_LIST_FAIL',
}
export enum OrderDeliverActionType {
  REQUEST = 'ORDER_DELIVER_REQUEST',
  SUCCESS = 'ORDER_DELIVER_SUCCESS',
  FAIL = 'ORDER_DELIVER_FAIL',
  RESET = 'ORDER_DELIVER_RESET',
}
