export enum UserLoginActionType {
  REQUEST = 'USER_LOGIN_REQUEST',
  SUCCESS = 'USER_LOGIN_SUCCESS',
  FAIL = 'USER_LOGIN_FAIL',
  LOGOUT = 'USER_LOGIN_LOGOUT',
}

export enum UserRegisterActionType {
  REQUEST = 'USER_REGISTER_REQUEST',
  SUCCESS = 'USER_REGISTER_SUCCESS',
  FAIL = 'USER_REGISTER_FAIL',
}

export enum UserDetailActionType {
  REQUEST = 'USER_DETAIL_REQUEST',
  SUCCESS = 'USER_DETAIL_SUCCESS',
  FAIL = 'USER_DETAIL_FAIL',
  RESET = 'USER_DETAIL_RESET',
}

export enum UserUpdateProfileActionType {
  REQUEST = 'USER_UPDATE_REQUEST',
  SUCCESS = 'USER_UPDATE_SUCCESS',
  FAIL = 'USER_UPDATE_FAIL',
  RESET = 'USER_UPDATE_RESET',
}
export enum UserListActionType {
  REQUEST = 'USER_LIST_REQUEST',
  SUCCESS = 'USER_LIST_SUCCESS',
  FAIL = 'USER_LIST_FAIL',
  RESET = 'USER_LIST_RESET',
}

export enum UserDeleteActionType {
  REQUEST = 'USER_DELETE_REQUEST',
  SUCCESS = 'USER_DELETE_SUCCESS',
  FAIL = 'USER_DELETE_FAIL',
}

export enum UserUpdateActionType {
  REQUEST = 'USER_UPDATE_REQUEST',
  SUCCESS = 'USER_UPDATE_SUCCESS',
  FAIL = 'USER_UPDATE_FAIL',
  RESET = 'USER_UPDATE_RESET',
}
